name: Lint apt
on:
  push:
    branches:
      - main
    paths:
      - 'apt/sighub/**'
      - 'apt/test/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apt/sighub/**'
      - 'apt/test/**'

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ./apt
      run: |
        pip install pylint
        pip install -r requirements.txt
    - name: pylint
      working-directory: ./apt
      run: pylint sighub/*.py
