name: Test logtail
on:
  push:
    branches:
      - main
    paths:
      - 'logtail/sighub/**'
      - 'logtail/test/**'
  pull_request:
    branches:
      - main
    paths:
      - 'logtail/sighub/**'
      - 'logtail/test/**'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ./logtail
      run: pip install -r requirements.txt
    - name: Unittests
      working-directory: ./logtail
      run: python -m unittest test/*
